//RES FILE GENERATED BY DS-SERVERS
//VISIT ds-servers.com
maps/2000_2_enjoy.res
overviews/2000_2_enjoy.txt
overviews/2000_2_enjoy.bmp
sprites/fire.spr
models/2000_2_project/buzzer_teatp_toyota.mdl
/models/2000_2_project/pine.mdl
/models/2000_2_project/pc2.mdl
sound/ambience/biggun2.wav
sound/sga/dhd_button.wav
halflife.wad
2000_project.wad

sprites/b_teleball.spr