maps/allie_gator.res
models/acr/alliescat.mdl
models/acr/baby_headcrab_green.mdl
models/acr/domessic-rat3.mdl
models/acr/domessic-rat4.mdl
models/acr/icongibs.mdl
models/acr/momscat.mdl
models/acr/spore.mdl
models/acr/taggibs.mdl
sound/allie_gator/alf-kitty.wav
sound/allie_gator/catmad.wav
sound/allie_gator/foryou.wav
sound/allie_gator/meow.wav
sound/allie_gator/meow1.wav
sound/allie_gator/purr1.wav
sound/allie_gator/tweety06.wav
sound/allie_gator/tweety41.wav
sprites/acr/alligator.spr
sprites/acr/bbbkiller.spr
sprites/acr/ce.spr
sprites/acr/cg2.spr
sprites/acr/gl.spr
sprites/acr/handy.spr