// as_KVARTAL.res - created with RESGen v2.0 BETA 3.
// RESGen is made by Jeroen "ShadowLord" Bogers.
// For more info go to http://resgen.hltools.com
// or E-mail me at resgen@hltools.com.

// .res entries (83):
kvartal_outside.wad
kvartal_outside_w.wad
gfx/env/vostokup.tga
gfx/env/vostokdn.tga
gfx/env/vostoklf.tga
gfx/env/vostokrt.tga
gfx/env/vostokft.tga
gfx/env/vostokbk.tga
models/props/dumpster_lidclosed_green.mdl
models/props/dumpster_lidclosed.mdl
models/props/trash_02.mdl
models/props/trashv01.mdl
models/props/truck_large-brown.mdl
models/props/jeep-russian.mdl
sound/ambience/arcticwind4.wav
sound/ambience/trailer_wndinsidepark_loop.wav
sound/kvartal/winter_veter.wav
sound/school/biolab_windoutside_loop.wav
models/buzz/buzzer_teatp_ladasp.mdl
models/buzz/buzzer_teatp_toyota.mdl
models/buzz/buzzer_kt_gazel.mdl
models/chernobyl/furgon_kalash.mdl
models/props/rug_oriental-large3.mdl
sound/music/nirvana-smellsliketeenspirit.wav
models/props/light_bulb2.mdl
models/man/dom_kv_1.mdl
sound/kvartal/car_siren-1.wav
models/man/78rus_gazel_blue.mdl
models/man/78rus_ladasp.mdl
models/man/78rus_toyota_blue.mdl
models/chernobyl/budka_kalash.mdl
models/chernobyl/kotushka_kalash.mdl
models/props/pi_tree_nl.mdl
models/buzz/buzzer_kt_derevsew.mdl
models/man/grasdw.mdl
models/man/topol1w.mdl
models/props/pi_tree3_nl.mdl
models/props/pi_tree2_nl.mdl
models/props/pi_tree1_nl.mdl
models/man/bush_japan_group1_nl.mdl
models/props/pi_treeb_nl.mdl
models/props/boxsprings_wreck.mdl
models/props/mattress_wreck.mdl
models/props/shelves_warehouse.mdl
models/props/sink_small.mdl
models/props/washingmachine.mdl
models/props/bathroom_toilet_dirty.mdl
models/props/group_kitchen.mdl
models/props/toilet.mdl
models/props/furniture_group-hotel02.mdl
sound/music/fpg-dvigatel.wav
models/props/tree_pine.mdl
models/man/78rus_ladasp_orange.mdl
models/man/78rus_toyota_red.mdl
models/man/78rus_ladasp_blue.mdl
models/man/78rus_toyota.mdl
sound/music/bi2-varvara.wav
models/props/antenna_urban.mdl
sound/kvartal/arcticwind.wav
models/props/furniture_group-hall01.mdl
models/props/furniture_group-hotel01.mdl
models/props/furniture_group-wreck.mdl
models/man/sat.mdl
models/man/unitaz.mdl
models/man/racovina.mdl
models/man/byxlo_group1.mdl
models/man/radiator.mdl
sound/common/body_scream1.wav
models/man/dom_school-1.mdl
sound/kvartal/car_zil.wav
models/man/dm_g_truck.mdl
sound/kvartal/gavno.wav
models/man/shit.mdl
models/man/bush_evergreen_group1_nl.mdl
models/props/bicycle_dead.mdl
models/man/3dm_seagull.mdl
sound/ambience/arcticwind3.wav
models/man/hl2_apc001.mdl
models/props/bobik_rus-1.mdl
models/man/njeep.mdl
models/man/vans.mdl
models/man/78rus_icarus.mdl
sprites/glow01.spr
overviews/as_KVARTAL.txt
overviews/as_KVARTAL.bmp
maps/as_KVARTAL.res
maps/as_KVARTAL.txt
maps/as_KVARTAL_detail.txt
maps/as_KVARTAL.nav
as_KVARTAL_preview.jpg
as_KVARTAL_realmap.gif
as_KVARTAL_ReadMe_rus.txt
as_KVARTAL_wallpaper_2.jpg
as_KVARTAL_wallpaper.jpg