maps/battlegrounds.res
map/battlegrounds.cfg
sound/misc/tarzan2.wav 
sound/misc/meathead.wav
sound/misc/chknum.wav
sound/misc/beetle11.wav
sound/misc/912.wav
sound/misc/911.wav
sound/misc/cheater.wav
sound/misc/bendover.wav
sound/misc/cant_touch_this.wav
sound/misc/PEEKABOO.wav 
sound/misc/sam36.wav
sound/misc/outahere.wav
sound/misc/gotcha.wav
sound/misc/putemup.wav
sound/misc/Beatle26.wav
sound/misc/beback.wav
sound/misc/blabbermouth.wav
sound/misc/shovebutt.wav
sound/misc/iwishiha.wav
sound/misc/tensec.wav
sound/misc/whosaid.wav
sound/misc/nicemove.wav
sound/misc/behave2.wav
sound/misc/haha.wav
sound/misc/doh.wav
sound/misc/panther.wav
sound/misc/beav_gg.wav
sound/misc/official.wav
sound/misc/boogie.wav
sound/misc/homer_an.wav
sound/misc/feelgood.wav
sound/misc/bitedust5.wav
sound/misc/yehaw.wav
sound/misc/kinison.wav
sound/misc/meow.wav
sound/misc/youdick.wav
sound/misc/youllpay.wav
sound/misc/black.wav
sound/misc/homergay.wav
sound/misc/numbnuts.wav
sound/misc/meow.wav
models/player/acr_grumpy/acr_grumpy.mdl
models/player/Lobo/Lobo.mdl
models/player/baboon/baboon.mdl
models/player/AllieCat/AllieCat.mdl
models/player/NetTarget/NetTarget.mdl