//File generated by DS-Servers
//Visit https://ds-servers.com
//Download this map: https://ds-servers.com/maps/goldsrc/valve/camper_rats.html
halflife.wad
liquids.wad
decals.wad
sprites/enter1.spr
sprites/smoke.spr
overviews/camper_rats.txt
overviews/camper_rats.bmp
models/camper/big_man.mdl
models/camper/big_roach.mdl
models/camper/kitty_litter.mdl
models/camper/bigfatrat.mdl
models/camper/soup_can.mdl
models/camper/teapot.mdl
models/camper/big_lady.mdl
models/camper/mug.mdl
models/camper/palm_large.mdl
models/camper/tv.mdl
models/camper/gingerbreadman.mdl
models/camper/macaroni.mdl
models/camper/vhstapes.mdl
models/camper/mountaindew.mdl
models/camper/cheeziest.mdl
sound/roach/rch_die.wav
sound/roach/rch_walk.wav
sound/camper/gumdropbuttons.wav
sound/camper/whatsthis.wav
sound/camper/kettlewhistle.wav
sound/camper/icedump.wav
maps/camper_rats.bsp
maps/camper_rats.txt
models/camper/icecube.mdl
