//File generated by DS-Servers
//Visit https://ds-servers.com
//Download this map: https://ds-servers.com/maps/goldsrc/valve/creep_halloween_bash.html
halflife.wad
xeno.wad
sprites/greeneye.spr
sprites/blueeye.spr
sprites/redeye.spr
sprites/yelloweye.spr
sprites/flameskulls.spr
sprites/creepreaper.spr
sprites/creepghost.spr
sound/halloween2004/scream02.wav
sound/halloween2004/fly.wav
sound/halloween2004/exorcist04.wav
sound/halloween2004/laugh20e.wav
sound/halloween2004/f13th01.wav
sound/halloween2004/moan04.wav
sound/halloween2004/scream01.wav
sound/halloween2004/growl03.wav
sound/halloween2004/evilcat01e.wav
sound/halloween2004/heartbeat.wav
sound/halloween2004/grlscrm01e.wav
sound/halloween2004/groan02e.wav
sound/halloween2004/growl01.wav
sound/halloween2004/halloween.wav
sound/halloween2004/horror005.wav
sound/halloween2004/moans01.wav
sound/halloween2004/halloween-scare.wav
sound/halloween2004/therack.wav
gfx/env/towsercreepbk.tga
gfx/env/towsercreepdn.tga
gfx/env/towsercreepft.tga
gfx/env/towsercreeplf.tga
gfx/env/towsercreeprt.tga
gfx/env/towsercreepup.tga
maps/creep_halloween_bash.bsp
