models/player/applejack/applejack.mdl
models/player/applejack_2d/applejack_2d.mdl
models/player/fluttershy/fluttershy.mdl
models/player/fluttershy_2d/fluttershy_2d.mdl
models/player/pinkie/pinkie.mdl
models/player/pinkie_2d/pinkie_2d.mdl
models/player/rainbow/rainbow.mdl
models/player/rainbow_2d/rainbow_2d.mdl
models/player/rarity/rarity.mdl
models/player/rarity_2d/rarity_2d.mdl
models/player/twilight/twilight.mdl
models/player/twilight_2d/twilight_2d.mdl

models/player/applejack/applejack.bmp
models/player/applejack_2d/applejack_2d.bmp
models/player/fluttershy/fluttershy.bmp
models/player/fluttershy_2d/fluttershy_2d.bmp
models/player/pinkie/pinkie.bmp
models/player/pinkie_2d/pinkie_2d.bmp
models/player/rainbow/rainbow.bmp
models/player/rainbow_2d/rainbow_2d.bmp
models/player/rarity/rarity.bmp
models/player/rarity_2d/rarity_2d.bmp
models/player/twilight/twilight.bmp
models/player/twilight_2d/twilight_2d.bmp