//////////////////////////////////////////////////////////
// Resources file, created with 17buddies php script!!! //
// © Chapo 2005-2007 - Infos @ http://www.17buddies.net //
//          More than 15000 maps to download!           //
//                                                      //
//      Can you play all of our maps ?? Sure not!!      //
//////////////////////////////////////////////////////////
//
// Res file generated by mikado for 17Buddies.
//
// Map Name  : cs_bbicotka
//
// Download @: http://dwl.17buddies.net/link/map/6969/cs_bbicotka.html
//
//////////////////////////////////////////////////////////
gfx/env/cs_bbicotkaup.tga
gfx/env/cs_bbicotkadn.tga
gfx/env/cs_bbicotkalf.tga
gfx/env/cs_bbicotkart.tga
gfx/env/cs_bbicotkaft.tga
gfx/env/cs_bbicotkabk.tga

models/buzz/lip_bathroomsink.mdl
models/buzz/truba_big.mdl
models/hostage.mdl
models/scientist.mdl
 
sound/buzz/buzzer_liftstart.wav
sound/buzz/buzzer_mmanson.wav
sound/buzz/buzzer_rusgimn.wav
sound/buzz/buzzer_videofilm.wav
sound/buzz/buzzer_yLica.wav
sound/doors/doormove1.wav
sound/doors/doorstop1.wav
 
sprites/glow04.spr
sprites/buzz/buzzer_flower.spr
sprites/buzz/buzzer_grass.spr
sprites/buzz/buzzer_perilla.spr
sprites/buzz/buzzer_perilla2.spr
sprites/buzz/buzzer_perilla3.spr
sprites/buzz/buzzer_travka.spr
sprites/buzz/buzzer_travka2.spr
sprites/buzz/buzzer_travka3.spr
sprites/buzz/buzzer_zvetok.spr
 
overviews/cs_bbicotka.bmp
overviews/cs_bbicotka.txt
