// cs_kvartal.res - created with RESGen v2.0 BETA 3.
// RESGen is made by Jeroen "ShadowLord" Bogers.
// For more info go to http://resgen.hltools.com
// or E-mail me at resgen@hltools.com.

// .res entries (92):
kvartal_origin.wad
kvartal_outside.wad
cars_1.wad
kvartal_night.wad
gfx/env/havup.tga
gfx/env/havdn.tga
gfx/env/havlf.tga
gfx/env/havrt.tga
gfx/env/havft.tga
gfx/env/havbk.tga
models/props/dumpster_lidclosed_green.mdl
models/props/dumpster_lidclosed.mdl
models/props/trash_02.mdl
models/props/trashv01.mdl
models/props/truck_large-brown.mdl
models/props/jeep-russian.mdl
sound/school/dog4.wav
sound/school/city_sirenby.wav
sound/ambience/rain_loop_01.wav
sound/ambience/rain_inside_loop.wav
sound/school/biolab_windoutside_loop.wav
models/buzz/buzzer_teatp_ladasp.mdl
models/buzz/buzzer_teatp_toyota.mdl
models/buzz/buzzer_kt_gazel.mdl
models/chernobyl/furgon_kalash.mdl
models/props/bobik_rus-1.mdl
models/props/truck_russian-large_blue.mdl
models/props/rug_oriental-large3.mdl
sound/music/clubcavair-speeditup.wav
models/props/light_bulb2.mdl
models/man/dom_kv_1.mdl
sound/kvartal/car_siren-1.wav
models/man/78rus_gazel_blue.mdl
models/man/78rus_ladasp.mdl
models/man/78rus_toyota_blue.mdl
models/chernobyl/budka_kalash.mdl
models/chernobyl/kotushka_kalash.mdl
models/props/pi_tree.mdl
models/buzz/buzzer_kt_derevse.mdl
models/chernobyl/grasd.mdl
models/chernobyl/flo_grass.mdl
models/props/topol-2.mdl
models/props/pi_tree3.mdl
models/props/pi_tree2.mdl
models/props/pi_tree1.mdl
models/man/bush_japan_group1.mdl
models/props/pi_treeb.mdl
models/props/boxsprings_wreck.mdl
models/props/mattress_wreck.mdl
models/props/shelves_warehouse.mdl
models/props/deadguy_jungle.mdl
models/props/sink_small.mdl
models/props/washingmachine.mdl
models/props/bathroom_toilet_dirty.mdl
models/props/group_kitchen.mdl
models/props/toilet.mdl
models/props/furniture_group-hotel02.mdl
sound/music/metallica-stonedeadforever.wav
models/props/tree_pine.mdl
models/props/bush_japan_bush01.mdl
models/man/78rus_ladasp_orange.mdl
models/man/78rus_toyota_red.mdl
models/man/78rus_ladasp_blue.mdl
models/man/78rus_toyota.mdl
sound/music/uantonov[alb5]-track1.wav
models/props/antenna_urban.mdl
sound/kvartal/arcticwind.wav
models/props/furniture_group-hall01.mdl
models/props/furniture_group-hotel01.mdl
models/props/furniture_group-wreck.mdl
models/props/deadguy_euro.mdl
models/props/deadguy_desert.mdl
models/man/sat.mdl
models/man/unitaz.mdl
models/man/racovina.mdl
models/man/byxlo_group1.mdl
models/man/radiator.mdl
sound/common/body_scream1.wav
models/man/dom_school-1.mdl
sound/school/truck2.wav
models/man/dm_g_truck.mdl
sound/kvartal/gavno.wav
models/man/shit.mdl
models/man/bush_evergreen_group1.mdl
models/props/bicycle_dead.mdl
models/man/3dm_seagull.mdl
sprites/glow01.spr
models/hostages/us_gal.mdl
models/hostages/npc-scientist.mdl
sound/ambience/rain.wav
sound/ambience/thunder_clap.wav
sprites/laserbeam.spr
overviews/cs_KVARTAL.txt
overviews/cs_KVARTAL.bmp
maps/cs_KVARTAL.res
maps/cs_KVARTAL.txt
maps/cs_KVARTAL_detail.txt
maps/cs_KVARTAL.nav
cs_KVARTAL_realmap.gif
cs_KVARTAL_preview.jpg
cs_KVARTAL_ReadMe_rus.txt
cs_KVARTAL_wallpaper_2.jpg
cs_KVARTAL_wallpaper.jpg