gfx/env/villagebk.tga
gfx/env/villagedn.tga
gfx/env/villageft.tga
gfx/env/villagelf.tga
gfx/env/villagert.tga
gfx/env/villageup.tga
models/dm/apache.mdl
models/dm/helicopter.mdl
models/dm/jeep.mdl
models/dm/lightpole.mdl
models/dm/nuclear_truck.mdl
models/dm/palm.mdl
models/dm/palm_stub.mdl
models/dm/tank.mdl
models/dm/tree.mdl
models/dm/truck.mdl
sound/dm/khalid_survive.wav
sound/dm/wind_loop.wav