// csg_office_night.res - created with RESGen v2.0.2.
// RESGen is made by Jeroen "ShadowLord" Bogers,
// with serveral improvements and additions by Zero3Cool.
// For more info go to http://resgen.hltools.com

// .res entries (39):
gfx/env/skybox/sky_cs15_nightbk.tga
gfx/env/skybox/sky_cs15_nightdn.tga
gfx/env/skybox/sky_cs15_nightft.tga
gfx/env/skybox/sky_cs15_nightlf.tga
gfx/env/skybox/sky_cs15_nightrt.tga
gfx/env/skybox/sky_cs15_nightup.tga
models/hostage.mdl
models/props/cs_office/bankerwdw.mdl
models/props/cs_office/compmon.mdl
models/props/cs_office/fence03a.mdl
models/props/cs_office/flag_us.mdl
models/props/cs_office/glass.mdl
models/props/cs_office/light_hanging.mdl
models/props/cs_office/offchair.mdl
models/props/cs_office/office_boards.mdl
models/props/cs_office/office_building_number.mdl
models/props/cs_office/office_clouds.mdl
models/props/cs_office/office_paintings.mdl
models/props/cs_office/office_sb.mdl
models/props/cs_office/props_plants.mdl
models/props/cs_office/rolling_gate.mdl
models/props/cs_office/sign_office_park.mdl
models/props/cs_office/snowman.mdl
models/props/cs_office/stairs.mdl
models/props/cs_office/swat_van.mdl
models/props/de_dust/rusty_barrel.mdl
sound/csg/door_metal_gate_move1.wav
sound/csg/elev1.wav
sound/csg/elev2.wav
sound/csg/elev3.wav
sound/csg/elev4.wav
sound/csg/office_garage_tone_01.wav
sound/csg/office_outside_driveby_02.wav
sound/csg/office_outside_tone_01.wav
sound/csg/OfficeNews.wav
sound/csg/pipes_active_loop.wav
sprites/2dprops/projector_img.spr
sprites/ledglow.spr
sprites/particles/Glow.spr

models/player/cs_arctic/cs_arctic.mdl
models/player/cs_gign/cs_gign.mdl
models/player/cs_gsg9/cs_gsg9.mdl
models/player/cs_guerilla/cs_guerilla.mdl
models/player/cs_leet/cs_leet.mdl
models/player/cs_sas/cs_sas.mdl
models/player/cs_terror/cs_terror.mdl
models/player/cs_urban/cs_urban.mdl
models/player/cs_vip/cs_vip.mdl
models/player/csb_arab/csb_arab.mdl
models/player/cscz_arctic/cscz_arctic.mdl
models/player/cscz_gign/cscz_gign.mdl
models/player/cscz_guerilla/cscz_guerilla.mdl
models/player/cscz_leet/cscz_leet.mdl
models/player/cscz_militia/cscz_militia.mdl
models/player/cscz_sas/cscz_sas.mdl
models/player/cscz_spetsnaz/cscz_spetsnaz.mdl
models/player/cscz_terror/cscz_terror.mdl
models/player/cscz_urban/cscz_urban.mdl
models/player/cscz_vip/cscz_vip.mdl
models/player/css_arctic/css_arctic.mdl
models/player/css_gign/css_gign.mdl
models/player/css_guerilla/css_guerilla.mdl
models/player/css_gsg9/css_gsg9.mdl
models/player/css_leet/css_leet.mdl
models/player/css_sas/css_sas.mdl
models/player/css_terror/css_terror.mdl
models/player/css_urban/css_urban.mdl
models/player/guerilla/guerilla.mdl
models/player/hostage_1/hostage_1.mdl
models/player/hostage_2/hostage_2.mdl

models/player/cs_arctic/cs_arctic.bmp
models/player/cs_gign/cs_gign.bmp
models/player/cs_gsg9/cs_gsg9.bmp
models/player/cs_guerilla/cs_guerilla.bmp
models/player/cs_leet/cs_leet.bmp
models/player/cs_sas/cs_sas.bmp
models/player/cs_terror/cs_terror.bmp
models/player/cs_urban/cs_urban.bmp
models/player/cs_vip/cs_vip.bmp
models/player/csb_arab/csb_arab.bmp
models/player/cscz_arctic/cscz_arctic.bmp
models/player/cscz_gign/cscz_gign.bmp
models/player/cscz_guerilla/cscz_guerilla.bmp
models/player/cscz_leet/cscz_leet.bmp
models/player/cscz_militia/cscz_militia.bmp
models/player/cscz_sas/cscz_sas.bmp
models/player/cscz_spetsnaz/cscz_spetsnaz.bmp
models/player/cscz_terror/cscz_terror.bmp
models/player/cscz_urban/cscz_urban.bmp
models/player/cscz_vip/cscz_vip.bmp
models/player/css_arctic/css_arctic.bmp
models/player/css_gign/css_gign.bmp
models/player/css_guerilla/css_guerilla.bmp
models/player/css_gsg9/css_gsg9.bmp
models/player/css_leet/css_leet.bmp
models/player/css_sas/css_sas.bmp
models/player/css_terror/css_terror.bmp
models/player/css_urban/css_urban.bmp
models/player/guerilla/guerilla.bmp
models/player/hostage_1/hostage_1.bmp
models/player/hostage_2/hostage_2.bmp
