//////////////////////////////////////////////////////////
// Resources file, created with 17buddies php script!!! //
// © Chapo 2005-2007 - Infos @ http://www.17buddies.net //
//          More than 15000 maps to download!           //
//                                                      //
//      Can you play all of our maps ?? Sure not!!      //
//////////////////////////////////////////////////////////
//
// Res file generated by mikado for 17Buddies.
//
// Map Name  : de_rats6_v1
//
// Download @: http://dwl.17buddies.net/link/map/12450/de_rats6_v1.html
//
//////////////////////////////////////////////////////////
gfx/env/forestup.tga
gfx/env/forestdn.tga
gfx/env/forestlf.tga
gfx/env/forestrt.tga
gfx/env/forestft.tga
gfx/env/forestbk.tga
sound/ambience/matrix.wav
sound/ambience/wind1.wav
