//////////////////////////////////////////////////////////
// Resources file, created with 17buddies php script!!! //
// © Chapo 2005-2007 - Infos @ http://www.17buddies.net //
//          More than 15000 maps to download!           //
//                                                      //
//      Can you play all of our maps ?? Sure not!!      //
//////////////////////////////////////////////////////////
//
// Res file generated by mikado for 17Buddies.
//
// Map Name  : de_rats_motel
//
// Download @: http://dwl.17buddies.net/link/map/3398/de_rats_motel.html
//
//////////////////////////////////////////////////////////
gfx/env/backalleyup.tga
gfx/env/backalleydn.tga
gfx/env/backalleylf.tga
gfx/env/backalleyrt.tga
gfx/env/backalleyft.tga
gfx/env/backalleybk.tga

sound/rats79/wind.wav

sprites/snow.spr
