//File generated by DS-Servers
//Visit https://ds-servers.com
//Download this map: https://ds-servers.com/maps/goldsrc/valve/de_springfield.html
halflife.wad
sprites/fire.spr
cstrike.wad
sound/ambience/fallscream.wav
models/lv_bottle.mdl
overviews/de_springfield.bmp
models/springers/krusty.mdl
sound/simpsons/fire.wav
sound/simpsons/brockman.wav
sound/simpsons/otto.wav
sound/simpsons/yellow.wav
sound/simpsons/intro.wav
sound/simpsons/krusty.wav
sound/simpsons/kem.wav
sound/simpsons/burp.wav
gfx/env/simp2_bk.tga
gfx/env/simp2_dn.tga
gfx/env/simp2_ft.tga
gfx/env/simp2_lf.tga
gfx/env/simp2_rt.tga
gfx/env/simp2_up.tga
maps/de_springfield.bsp
maps/de_springfield.txt
overviews/de_springfield.txt
