// V:\jwatchface\dm_teterevyatnik_beta\maps\dm_teterevyatnik_beta.res - created with RESGen v1.10
// RESGen is made by Jeroen "ShadowLord" Bogers
// URL: http://www.unitedadmins.com/mapRESGEN.asp
// E-MAIL: resgen@hltools.com
// Res creation date, GMT timezone (dd-mm-yyyy): 23-02-2026

// .res entries:
gfx/env/kone4ka_up.tga
gfx/env/kone4ka_dn.tga
gfx/env/kone4ka_lf.tga
gfx/env/kone4ka_rt.tga
gfx/env/kone4ka_ft.tga
gfx/env/kone4ka_bk.tga
models/dm_teterevyatnik/bush_teterev.mdl
sound/dm_teterevyatnik/truck1.wav
sound/dm_teterevyatnik/truck2.wav
sound/dm_teterevyatnik/electric_hum2.wav
sound/dm_teterevyatnik/wind2.wav
models/dm_teterevyatnik/tree1_de_konechka.mdl
models/dm_teterevyatnik/tree2_de_konechka.mdl
models/dm_teterevyatnik/tree3_de_konechka.mdl
sound/dm_teterevyatnik/musictrack1.wav
sound/dm_teterevyatnik/musictrack2.wav
sound/dm_teterevyatnik/musictrack3.wav
sound/dm_teterevyatnik/musictrack4.wav
sound/dm_teterevyatnik/musictrack5.wav
models/dm_teterevyatnik/byxlo1.mdl
sprites/dm_teterevyatnik/perila1blue.spr
sprites/laserbeam.spr
sprites/dm_teterevyatnik/perila2blue.spr
sprites/dm_teterevyatnik/perila1blue2.spr
sprites/dm_teterevyatnik/perila2blue2.spr
sprites/dm_teterevyatnik/perilla3blue1.spr
sprites/dm_teterevyatnik/perilla3blue2.spr
sprites/dm_teterevyatnik/cable3.spr
sprites/dm_teterevyatnik/cable4.spr
sprites/flare3.spr
sprites/dm_teterevyatnik/perilla3green1.spr
sprites/dm_teterevyatnik/perilla3green2.spr
sprites/dm_teterevyatnik/perilla2green.spr
sprites/dm_teterevyatnik/perilla1green.spr
sprites/dm_teterevyatnik/perila1green2.spr
sprites/dm_teterevyatnik/perila2green2.spr
sound/dm_teterevyatnik/hummingmachine.wav
sound/dm_teterevyatnik/alien_creeper.wav
models/dm_teterevyatnik/blyat_thin3.mdl
models/dm_teterevyatnik/bigrat2.mdl
sound/ambience/alien_creeper.wav

models/player/cs_arctic/cs_arctic.mdl
models/player/cs_gign/cs_gign.mdl
models/player/cs_gsg9/cs_gsg9.mdl
models/player/cs_guerilla/cs_guerilla.mdl
models/player/cs_leet/cs_leet.mdl
models/player/cs_sas/cs_sas.mdl
models/player/cs_terror/cs_terror.mdl
models/player/cs_urban/cs_urban.mdl
models/player/cs_vip/cs_vip.mdl
models/player/csb_arab/csb_arab.mdl
models/player/cscz_arctic/cscz_arctic.mdl
models/player/cscz_gign/cscz_gign.mdl
models/player/cscz_guerilla/cscz_guerilla.mdl
models/player/cscz_leet/cscz_leet.mdl
models/player/cscz_militia/cscz_militia.mdl
models/player/cscz_sas/cscz_sas.mdl
models/player/cscz_spetsnaz/cscz_spetsnaz.mdl
models/player/cscz_terror/cscz_terror.mdl
models/player/cscz_urban/cscz_urban.mdl
models/player/cscz_vip/cscz_vip.mdl
models/player/css_arctic/css_arctic.mdl
models/player/css_gign/css_gign.mdl
models/player/css_guerilla/css_guerilla.mdl
models/player/css_gsg9/css_gsg9.mdl
models/player/css_leet/css_leet.mdl
models/player/css_sas/css_sas.mdl
models/player/css_terror/css_terror.mdl
models/player/css_urban/css_urban.mdl
models/player/guerilla/guerilla.mdl
models/player/hostage_1/hostage_1.mdl
models/player/hostage_2/hostage_2.mdl

models/player/cs_arctic/cs_arctic.bmp
models/player/cs_gign/cs_gign.bmp
models/player/cs_gsg9/cs_gsg9.bmp
models/player/cs_guerilla/cs_guerilla.bmp
models/player/cs_leet/cs_leet.bmp
models/player/cs_sas/cs_sas.bmp
models/player/cs_terror/cs_terror.bmp
models/player/cs_urban/cs_urban.bmp
models/player/cs_vip/cs_vip.bmp
models/player/csb_arab/csb_arab.bmp
models/player/cscz_arctic/cscz_arctic.bmp
models/player/cscz_gign/cscz_gign.bmp
models/player/cscz_guerilla/cscz_guerilla.bmp
models/player/cscz_leet/cscz_leet.bmp
models/player/cscz_militia/cscz_militia.bmp
models/player/cscz_sas/cscz_sas.bmp
models/player/cscz_spetsnaz/cscz_spetsnaz.bmp
models/player/cscz_terror/cscz_terror.bmp
models/player/cscz_urban/cscz_urban.bmp
models/player/cscz_vip/cscz_vip.bmp
models/player/css_arctic/css_arctic.bmp
models/player/css_gign/css_gign.bmp
models/player/css_guerilla/css_guerilla.bmp
models/player/css_gsg9/css_gsg9.bmp
models/player/css_leet/css_leet.bmp
models/player/css_sas/css_sas.bmp
models/player/css_terror/css_terror.bmp
models/player/css_urban/css_urban.bmp
models/player/guerilla/guerilla.bmp
models/player/hostage_1/hostage_1.bmp
models/player/hostage_2/hostage_2.bmp
