// es_kvartal.res - created with RESGen v2.0 BETA 3.
// RESGen is made by Jeroen "ShadowLord" Bogers.
// For more info go to http://resgen.hltools.com
// or E-mail me at resgen@hltools.com.

// .res entries (72):
kvartal.wad
cars_buz_1.wad
gfx/env/grnplsnt_rotup.tga
gfx/env/grnplsnt_rotdn.tga
gfx/env/grnplsnt_rotlf.tga
gfx/env/grnplsnt_rotrt.tga
gfx/env/grnplsnt_rotft.tga
gfx/env/grnplsnt_rotbk.tga
models/props/dumpster_lidclosed_green.mdl
models/props/dumpster_lidclosed.mdl
models/props/trash_02.mdl
models/props/trashv01.mdl
models/props/truck_large-brown.mdl
models/props/jeep-russian.mdl
sound/school/dog4.wav
sound/school/city_sirenby.wav
sound/school/toruko_verynicebirdys_loop.wav
sound/school/city_loop2.wav
sound/school/fastline_station3.wav
sound/school/biolab_windoutside_loop.wav
models/buzz/buzzer_teatp_ladasp.mdl
models/buzz/buzzer_teatp_toyota.mdl
models/buzz/buzzer_kt_gazel.mdl
models/chernobyl/furgon_kalash.mdl
models/props/bobik_rus-1.mdl
models/props/truck_russian-large_blue.mdl
models/props/car_hatchback.mdl
models/props/car_sedan.mdl
models/props/rug_oriental-large3.mdl
sound/music/djrenatcb-12.wav
models/props/light_bulb2.mdl
models/man/dom_kv_1.mdl
sound/kvartal/car_siren-1.wav
models/man/78rus_gazel_blue.mdl
models/man/78rus_ladasp.mdl
models/man/78rus_toyota_blue.mdl
models/chernobyl/budka_kalash.mdl
models/chernobyl/kotushka_kalash.mdl
models/props/pi_tree.mdl
models/buzz/buzzer_kt_derevse.mdl
models/chernobyl/grasd.mdl
models/chernobyl/flo_grass.mdl
models/props/topol-2.mdl
models/props/pi_tree3.mdl
models/props/pi_tree2.mdl
models/props/pi_tree1.mdl
models/props/bush_evergreen.mdl
models/props/bush_japan_bush01.mdl
models/props/pi_treeb.mdl
models/props/boxsprings_wreck.mdl
models/props/mattress_wreck.mdl
models/props/shelves_warehouse.mdl
models/props/deadguy_jungle.mdl
models/props/sink_small.mdl
models/props/washingmachine.mdl
models/props/bathroom_toilet_dirty.mdl
models/props/group_kitchen.mdl
models/props/toilet.mdl
models/props/furniture_group-hotel02.mdl
sound/music/sectorgaza-pesenka.wav
models/props/tree_pine.mdl
models/man/78rus_ladasp_orange.mdl
models/man/78rus_toyota_red.mdl
models/man/78rus_ladasp_blue.mdl
models/man/78rus_toyota.mdl
sound/music/aria-angel.wav
models/props/antenna_urban.mdl
models/kueb/kalash_rusvodka.mdl
sound/kvartal/arcticwind.wav
models/props/furniture_group-hall01.mdl
models/props/furniture_group-hotel01.mdl
models/props/furniture_group-wreck.mdl
