//File generated by DS-Servers
//Visit https://ds-servers.com
//Download this map: https://ds-servers.com/maps/goldsrc/valve/halloween_2009.html
models/halloween_killbox/jumppadpum.mdl
models/halloween_killbox/pumpkintop.mdl
models/halloween_killbox/gonome.mdl
models/halloween_killbox/hungerslavehell.mdl
models/halloween_killbox/bonecrab.mdl
models/halloween_killbox/puppeh.mdl
sprites/halloween_killbox/skell1.spr
sprites/halloween_killbox/skeel2.spr
sprites/halloween_killbox/skull.spr
sprites/halloween_killbox/spell.spr
sound/halloween_killbox/elec_explo.wav
sound/halloween_killbox/bleedout.wav
sound/halloween_killbox/hungersh.wav
sound/halloween_killbox/jp4.wav
sound/halloween_killbox/jp1.wav
sound/halloween_killbox/jp2.wav
sound/halloween_killbox/jp3.wav
sound/halloween_killbox/wind.wav
sound/halloween_killbox/zombie.wav
sound/halloween_killbox/getout.wav
gfx/env/eygrip257_bk.tga
gfx/env/eygrip257_dn.tga
gfx/env/eygrip257_ft.tga
gfx/env/eygrip257_lf.tga
gfx/env/eygrip257_rt.tga
gfx/env/eygrip257_up.tga
models/halloween_killbox/bonecrabt.mdl
maps/halloween_2009.bsp
