//File generated by DS-Servers
//Visit https://ds-servers.com
//Download this map: https://ds-servers.com/maps/goldsrc/valve/hldm_museum.html
sprites/glow02.spr
sprites/glow04.spr
gfx/env/city_daybk.tga
gfx/env/city_daydn.tga
gfx/env/city_dayft.tga
gfx/env/city_daylf.tga
gfx/env/city_dayrt.tga
gfx/env/city_dayup.tga
models/jinx/xen_plant4.mdl
models/jinx/xen_plant8.mdl
models/jinx/w_grenadet.mdl
models/jinx/couch1.mdl
models/jinx/xen_plant1.mdl
models/jinx/w_grenade.mdl
maps/hldm_museum.bsp
