//File generated by DS-Servers
//Visit https://ds-servers.com
//Download this map: https://ds-servers.com/maps/goldsrc/valve/kitkat_disco.html
halflife.wad
models/bigrat.mdl
gfx/env/cloud9_bk.tga
gfx/env/cloud9_dn.tga
gfx/env/cloud9_ft.tga
gfx/env/cloud9_lf.tga
gfx/env/cloud9_rt.tga
gfx/env/cloud9_up.tga
sprites/laserbeam.spr
sprites/disco/disco_ball.spr
sprites/disco/tanq_wine.spr
sprites/disco/vodka_wine.spr
sprites/disco/trip.spr
sprites/disco/margarita.spr
sprites/disco/np_beer.spr
sprites/disco/beer.spr
sprites/disco/sexysmoke.spr
sprites/disco/vod_ups.spr
sprites/disco/fcb.spr
sprites/disco/travolta.spr
sprites/disco/sign.spr
sprites/disco/sign5.spr
sound/disco/boneless_looped.wav
maps/kitkat_disco.bsp
maps/kitkat_disco.txt
