//File generated by DS-Servers
//Visit https://ds-servers.com
//Download this map: https://ds-servers.com/maps/goldsrc/valve/kitkat_express.html
halflife.wad
sprites/stmbal1.spr
sound/ambience/steamjet1.wav
gfx/env/riverscape1bk.tga
gfx/env/riverscape1dn.tga
gfx/env/riverscape1ft.tga
gfx/env/riverscape1lf.tga
gfx/env/riverscape1rt.tga
gfx/env/riverscape1up.tga
sprites/xsmoke3.spr
overviews/kitkat_express.txt
overviews/kitkat_express.bmp
sprites/express3.spr
sprites/express4.spr
sound/express/slkiteki.wav
sound/plats/ttrain_brake1.wav
sound/express/welcome.wav
sound/express/tonedial.wav
sound/scientist/hello2.wav
sound/plats/ttrain4.wav
maps/kitkat_express.bsp
maps/kitkat_express.txt
models/glassgibs.mdl
