//File generated by DS-Servers
//Visit https://ds-servers.com
//Download this map: https://ds-servers.com/maps/goldsrc/valve/kitkat_urban.html
halflife.wad
liquids.wad
decals.wad
sound/ambience/crtnoise.wav
sprites/moths.spr
gfx/env/chaoscitybk.tga
gfx/env/chaoscitydn.tga
gfx/env/chaoscityft.tga
gfx/env/chaoscitylf.tga
gfx/env/chaoscityrt.tga
gfx/env/chaoscityup.tga
models/uplant1.mdl
models/uplant1t.mdl
sprites/wdrip2.spr
sound/urban/trash.wav
sound/urban/bkitty.wav
sound/urban/woohoo2.wav
sound/urban/chaching.wav
sound/urban/sickness.wav
sound/urban/drip.wav
sound/urban/headhunter.wav
sound/urban/cat06.wav
maps/kitkat_urban.bsp
sound/urban/police.wav
sound/urban/citynoise1.wav
maps/kitkat_urban.txt
