//File generated by DS-Servers
//Visit https://ds-servers.com
//Download this map: https://ds-servers.com/maps/goldsrc/valve/kitkat_gallery.html
halflife.wad
liquids.wad
decals.wad
sprites/fire.spr
gfx/env/spacebk.tga
gfx/env/spacedn.tga
gfx/env/spaceft.tga
gfx/env/spacelf.tga
gfx/env/spacert.tga
gfx/env/spaceup.tga
sprites/c-tele1.spr
maps/kitkat_gallery.bsp
sprites/laserbeam.spr
