//File generated by DS-Servers
//Visit https://ds-servers.com
//Download this map: https://ds-servers.com/maps/goldsrc/valve/kitkat_factory.html
halflife.wad
liquids.wad
decals.wad
sprites/fire.spr
sprites/xsmoke1.spr
gfx/env/broodingbk.tga
gfx/env/broodingdn.tga
gfx/env/broodingft.tga
gfx/env/broodinglf.tga
gfx/env/broodingrt.tga
gfx/env/broodingup.tga
sound/ambience/rotormachine.wav
sound/ambience/pounder.wav
sound/ambience/burning1.wav
sound/ambience/boomer.wav
sound/ambience/hammer.wav
sprites/smoke.spr
sound/ambience/alien_builder.wav
sprites/xsmoke4.spr
sprites/bluejet1.spr
maps/kitkat_factory.bsp
maps/kitkat_factory.txt
