//File generated by DS-Servers
//Visit https://ds-servers.com
//Download this map: https://ds-servers.com/maps/goldsrc/valve/kitkat_klub.html
halflife.wad
liquids.wad
decals.wad
sound/ambience/breather.wav
sound/ambience/waterfall3.wav
sprites/smoke.spr
models/holo.mdl
sprites/bubble.spr
sound/kitkat_klub/control.wav
sound/kitkat_klub/needledropnoise.wav
sound/kitkat_klub/pacman.wav
sound/kitkat_klub/pacman2.wav
sound/kitkat_klub/fart.wav
sound/scientist/peculiarodor.wav
sound/kitkat_klub/fart3.wav
sound/kitkat_klub/bubblewet.wav
sound/scientist/whoresponsible.wav
sound/kitkat_klub/splash1.wav
sound/kitkat_klub/dialtone.wav
sound/kitkat_klub/rotarydial.wav
sound/kitkat_klub/teleph.wav
sound/scientist/hellothere.wav
sound/kitkat_klub/pourbeer.wav
gfx/env/city2bk.tga
gfx/env/city2dn.tga
gfx/env/city2ft.tga
gfx/env/city2lf.tga
gfx/env/city2rt.tga
gfx/env/city2up.tga
maps/kitkat_klub.bsp
maps/kitkat_klub.txt
