//File generated by DS-Servers
//Visit https://ds-servers.com
//Download this map: https://ds-servers.com/maps/goldsrc/valve/kitkat_kasino2.html
sprites/glow01.spr
gfx/env/city_nitebk.tga
gfx/env/city_nitedn.tga
gfx/env/city_niteft.tga
gfx/env/city_nitelf.tga
gfx/env/city_nitert.tga
gfx/env/city_niteup.tga
models/kasino2/sword_japan_stand.mdl
sprites/kasino2/glow01.spr
models/kasino2/banzai_tree.mdl
models/kasino2/blondbab1.mdl
models/kasino2/gins_butts.mdl
models/kasino2/cobra.mdl
models/kasino2/plant_palm.mdl
sprites/kasino2/sqiggle.spr
sprites/kasino2/bbkk.spr
sprites/kasino2/ddd.spr
models/kasino2/3dm_hossie02.mdl
sprites/kasino2/kkkkk.spr
sprites/kasino2/jackpotkk.spr
models/kasino2/gold_red5.mdl
models/kasino2/gold_blue5.mdl
models/kasino2/kkbar.mdl
sound/kasino2/venge.wav
sound/kasino2/bandit.wav
sound/kasino2/payout.wav
sound/kasino2/head_tremor.wav
sound/kasino2/vegas_slots.wav
maps/kitkat_kasino2.bsp
