//File generated by DS-Servers
//Visit https://ds-servers.com
//Download this map: https://ds-servers.com/maps/goldsrc/valve/kitkat_kasino.html
halflife.wad
liquids.wad
sound/ambience/waterfall2.wav
gfx/env/chaoscitybk.tga
gfx/env/chaoscitydn.tga
gfx/env/chaoscityft.tga
gfx/env/chaoscitylf.tga
gfx/env/chaoscityrt.tga
gfx/env/chaoscityup.tga
models/casino/angesmoke.mdl
sound/casino/lv_fruitwin.wav
sound/casino/slotmach.wav
sound/casino/coinout.wav
sound/casino/277.wav
sound/casino/lv_fruit2.wav
sound/casino/bigwin1.wav
sound/casino/casino01.wav
sound/casino/cards03.wav
sound/casino/phone.wav
sound/casino/hello2.wav
sound/casino/startle7.wav
sound/casino/startle3.wav
sound/casino/sneeze.wav
sound/casino/shutup.wav
sound/casino/lv_jubilee.wav
sound/casino/welcome.wav
sound/casino/twhist.wav
sound/casino/woot.wav
maps/kitkat_kasino.bsp
maps/kitkat_kasino.txt
