gfx/env/monoup.tga
gfx/env/monodn.tga
gfx/env/monolf.tga
gfx/env/monort.tga
gfx/env/monoft.tga
gfx/env/monobk.tga
sound/monorail/engine.wav
sound/monorail/helicopter1.wav
sound/monorail/helicopter2.wav
sound/monorail/jet1.wav
sound/monorail/jet2.wav
sound/monorail/sp_fense.wav
sound/monorail/sp_waterfall1.wav
sound/monorail/sp_windloop.wav
sound/monorail/winddd.wav
models/monorail/bush1.mdl
models/monorail/bush2.mdl
models/monorail/bush3.mdl
models/monorail/dolly.mdl
models/monorail/fire_extinguisher.mdl
models/monorail/generator.mdl
models/monorail/lab_oscilliscope.mdl
models/monorail/sink_small.mdl
models/monorail/toilet_dirty.mdl
models/monorail/trash_trashcan.mdl
models/monorail/tree_noleaves.mdl