//File generated by DS-Servers
//Visit https://ds-servers.com
//Download this map: https://ds-servers.com/maps/goldsrc/valve/oceanfront.html
halflife.wad
gfx/env/tropicalbk.tga
gfx/env/tropicaldn.tga
gfx/env/tropicalft.tga
gfx/env/tropicallf.tga
gfx/env/tropicalrt.tga
gfx/env/tropicalup.tga
models/oceanfront/prop_rimpalm1a.mdl
models/oceanfront/fern3.mdl
models/oceanfront/prop_rimpalm1b.mdl
models/oceanfront/prop_svou.mdl
models/oceanfront/flowers.mdl
models/oceanfront/3dm_parasol.mdl
models/oceanfront/brunet.mdl
models/oceanfront/prop_wingstatue.mdl
models/oceanfront/blondbab.mdl
models/oceanfront/blondbab1.mdl
models/oceanfront/doc_seagull.mdl
models/oceanfront/orioke2.mdl
models/oceanfront/bigrat.mdl
models/oceanfront/plant_palm.mdl
models/oceanfront/lil_pum.mdl
sprites/oceanfront/express3.spr
sound/oceanfront/stone_jetty.wav
sound/oceanfront/f_wow.wav
sound/oceanfront/drain.wav
sound/oceanfront/makemyheart_looped.wav
maps/oceanfront.bsp
maps/oceanfront.txt
