//File generated by DS-Servers
//Visit https://ds-servers.com
//Download this map: https://ds-servers.com/maps/goldsrc/valve/parkinglot_v2.html
halflife.wad
liquids.wad
xeno.wad
sprites/glow01.spr
spraypaint.wad
sound/ambience/wind2.wav
sound/ambience/tankidle2.wav
opfor.wad
decals.wad
sound//ambience/industrial4.wav
gfx/env/duskbk.tga
gfx/env/duskdn.tga
gfx/env/duskft.tga
gfx/env/dusklf.tga
gfx/env/duskrt.tga
gfx/env/duskup.tga
cached.wad
tempdecal.wad
maps/parkinglot_v2.bsp
