//File generated by DS-Servers
//Visit https://ds-servers.com
//Download this map: https://ds-servers.com/maps/goldsrc/valve/rats_2001.html
halflife.wad
liquids.wad
xeno.wad
sprites/glow01.spr
decals.wad
sprites/xsmoke1.spr
sound/ambience/steamjet1.wav
sound/apache/ap_rotor3.wav
gfx/env/duskbk.tga
gfx/env/duskdn.tga
gfx/env/duskft.tga
gfx/env/dusklf.tga
gfx/env/duskrt.tga
gfx/env/duskup.tga
maps/rats_2001.bsp
