maps/sc_escape.res
maps/sc_escape.txt
models/Xeroni/Asztal.mdl
models/Xeroni/bed_sick.mdl
models/Xeroni/body_arm.mdl
models/Xeroni/body_hand.mdl
models/Xeroni/body_head.mdl
models/Xeroni/body_leg.mdl
models/Xeroni/body_legs.mdl
models/Xeroni/body_legs2.mdl
models/Xeroni/bodybag.mdl
models/Xeroni/deadgign.mdl
models/Xeroni/hosp_optable_old_bloody.mdl
models/Xeroni/kille_lik_1.mdl
models/Xeroni/player2.mdl
models/Xeroni/trup1.mdl
models/Xeroni/cerberus.mdl
models/Xeroni/axe.mdl
models/Xeroni/deadman.mdl
sound/Xeroni/horror3.wav
sound/Xeroni/scream1.wav
sound/Xeroni/scream2.wav
sound/Xeroni/shaft.wav
sound/Xeroni/waterdrips1.wav
sound/Xeroni/wind_tunnel1.wav
sound/Xeroni/breathe1.wav
