//File generated by DS-Servers
//Visit https://ds-servers.com
//Download this map: https://ds-servers.com/maps/goldsrc/valve/the_creeps_house.html
halflife.wad
liquids.wad
xeno.wad
sound/ambience/waterfall2.wav
gfx/env/spacebk.tga
gfx/env/spacedn.tga
gfx/env/spaceft.tga
gfx/env/spacelf.tga
gfx/env/spacert.tga
gfx/env/spaceup.tga
sprites/xsmoke1.spr
sound/ambience/waterfall3.wav
sprites/hugeball.spr
maps/the_creeps_house.bsp
