maps/winter_city.res
station.wad
gfx/env/iceflow256_bk.tga
gfx/env/iceflow256_dn.tga
gfx/env/iceflow256_ft.tga
gfx/env/iceflow256_lf.tga
gfx/env/iceflow256_rt.tga
gfx/env/iceflow256_up.tga
sound/ambience/waterrun.wav
sound/winter_city/citynoise.wav
sound/winter_city/mcity.wav