//File generated by DS-Servers
//Visit https://ds-servers.com
//Download this map: https://ds-servers.com/maps/goldsrc/valve/xdm_stalkx.html
halflife.wad
liquids.wad
xeno.wad
decals.wad
gfx.wad
sprites/cexplo.spr
fonts.wad
sound/ambience/waterfall3.wav
sound/ambience/des_wind2.wav
sound/ambience/des_wind1.wav
sprites/ballsmoke.spr
gfx/env/morningbk.tga
gfx/env/morningdn.tga
gfx/env/morningft.tga
gfx/env/morninglf.tga
gfx/env/morningrt.tga
gfx/env/morningup.tga
maps/xdm_stalkx.bsp
