//File generated by DS-Servers
//Visit https://ds-servers.com
//Download this map: https://ds-servers.com/maps/goldsrc/valve/xdm_stalkyard.html
halflife.wad
liquids.wad
xeno.wad
decals.wad
gfx/env/nightbk.tga
gfx/env/nightdn.tga
gfx/env/nightft.tga
gfx/env/nightlf.tga
gfx/env/nightrt.tga
gfx/env/nightup.tga
gfx.wad
sprites/flare1.spr
sprites/muzzleflash2.spr
fonts.wad
sound/ambience/wind1.wav
sound/ambience/biggun1.wav
sound/ambience/crickets.wav
sound/ambience/mechwhine.wav
maps/xdm_stalkyard.bsp
