models/player/alyx_nude/alyx_nude.mdl
models/player/combine/combine.mdl
models/player/combine_assassin/combine_assassin.mdl
models/player/combine_elite/combine_elite.mdl
models/player/combine_prison/combine_prison.mdl
models/player/combinecop/combinecop.mdl
models/player/gordon_hl2/gordon_hl2.mdl
models/player/gordon_hl2_ver_hl1/gordon_hl2_ver_hl1.mdl
models/player/hl2_alyx/hl2_alyx.mdl
models/player/hl2_barney/hl2_barney.mdl
models/player/hl2_breen/hl2_breen.mdl
models/player/hl2_eli/hl2_eli.mdl
models/player/hl2_gman/hl2_gman.mdl
models/player/hl2_gordon/hl2_gordon.mdl
models/player/hl2_gordon2/hl2_gordon2.mdl
models/player/hl2_gordon3/hl2_gordon3.mdl
models/player/hl2_gordon4/hl2_gordon4.mdl
models/player/hl2_grigori/hl2_grigori.mdl
models/player/hl2_helmet/hl2_helmet.mdl
models/player/hl2_kleiner/hl2_kleiner.mdl
models/player/hl2_mossman/hl2_mossman.mdl
models/player/hl2_odessa/hl2_odessa.mdl
models/player/hl2_zombie/hl2_zombie.mdl
models/player/zombie_fast/zombie_fast.mdl

models/player/alyx_nude/alyx_nude.bmp
models/player/combine/combine.bmp
models/player/combine_assassin/combine_assassin.bmp
models/player/combine_elite/combine_elite.bmp
models/player/combine_prison/combine_prison.bmp
models/player/combinecop/combinecop.bmp
models/player/gordon_hl2/gordon_hl2.bmp
models/player/gordon_hl2_ver_hl1/gordon_hl2_ver_hl1.bmp
models/player/hl2_alyx/hl2_alyx.bmp
models/player/hl2_barney/hl2_barney.bmp
models/player/hl2_breen/hl2_breen.bmp
models/player/hl2_eli/hl2_eli.bmp
models/player/hl2_gman/hl2_gman.bmp
models/player/hl2_gordon/hl2_gordon.bmp
models/player/hl2_gordon2/hl2_gordon2.bmp
models/player/hl2_gordon3/hl2_gordon3.bmp
models/player/hl2_gordon4/hl2_gordon4.bmp
models/player/hl2_grigori/hl2_grigori.bmp
models/player/hl2_helmet/hl2_helmet.bmp
models/player/hl2_kleiner/hl2_kleiner.bmp
models/player/hl2_mossman/hl2_mossman.bmp
models/player/hl2_odessa/hl2_odessa.bmp
models/player/hl2_zombie/hl2_zombie.bmp
models/player/zombie_fast/zombie_fast.bmp